language: java

before_script: cd recaf-runtime

jdk:
- oraclejdk8

addons:
  apt:
      packages:
            - oracle-java8-installer
            
notifications:
  slack: cwi-swat:mE7iJhJBjCpYUb86OmDz53Qf
  email: false
