language: java

addons:
    apt:
        packages:
              - oracle-java8-installer

script: mvn -DGEN=false clean dependency:copy-dependencies test

notifications:
  slack: cwi-swat:mE7iJhJBjCpYUb86OmDz53Qf
  email: false
