language: java

jdk:
- oraclejdk8

addons:
  apt:
      packages:
            - oracle-java8-installer

script: mvn clean test

notifications:
  slack: cwi-swat:mE7iJhJBjCpYUb86OmDz53Qf
  email: false
