language: java

jdk:
- oraclejdk8

script: mvn -DGEN=false clean dependency:copy-dependencies test

notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2112ed37cf625ee2e486
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
